name: Blog CI/CD

on:
  push:
    branches: 
      - hexo-blog-backup

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Setup node
      # 设置 node.js 环境
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache node modules
     # 设置包缓存目录，避免每次下载
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install hexo dependencies
      run: |
        npm install hexo-cli gulp -g
        npm install

    - name: Generate files
      run: |
        hexo clean
        hexo generate

    - name: Execute gulp task
      run: gulp

    - name: Deploy hexo blog
      env: 
        REPO: github.com/yifanzheng/yifanzheng.github.io
      run: |
        git clone "https://$REPO" deploy_git
        mv ./deploy_git/.git ./public/
        cd ./public
        git config user.name "yifanzheng"
        git config user.email "zhengyifan1996@outlook.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$REPO" master:master
        