name: Deploy GitHub Pages

# 触发条件：在 push 到 hexo 源码备份分支后
on:
  push:
    branches:
      - hexo-blog-backup
    # 下列文件的变更不触发部署，可以自行添加
    paths-ignore:   
      - README.md
      - LICENSE

# 任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
        mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        PATH=~/.npm-global/bin:$PATH
        npm install -g hexo-cli 
        npm install

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master